networks:
  proxy:
    external: false
    name: proxy

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command: 
      - --log.level=WARN
      - --api.insecure=false
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure=true
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.email={{ TRAEFIK_LETSENCRYPT_EMAIL }}
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=ionos
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.delayBeforeCheck=0
      - --providers.file.filename=/dynamic.yml
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./data/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/acme.json:/acme.json
      - ./data/dynamic.yml:/dynamic.yml
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik.rule=Host(`{{ TRAEFIK_PROXY_HOST }}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls.options=default
      - traefik.http.routers.traefik.middlewares=authelia@docker
