---
theme: dark

jwt_secret: "{{ AUTHELIA_JWT_SECRET }}"
default_redirection_url: "{{ AUTHELIA_DEFAULT_REDIRECTION_URL}}"

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

totp:
  issuer: "{{ AUTHELIA_PROXY_HOST }}"

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: allow
  rules:
    {% for rule in AUTHELIA_ACCESS_CONTROL_RULES: %}
- domain: {{ rule.domain }}
      policy: {{ rule.policy }}
    {% endfor %}

session:
  name: authelia_session
  domain: a.borgardt.me
  secret: "{{ AUTHELIA_SESSION_SECRET }}"
  same_site: lax
  expiration: 1h
  inactivity: 15m
  remember_me_duration: 1M

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 600

storage:
  encryption_key: "{{ AUTHELIA_STORAGE_SECRET }}"
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: {{ AUTHELIA_SMTP_USER }}
    password: {{ AUTHELIA_SMTP_PASSWORD }}
    host: smtp.gmail.com
    port: 587
    sender: sso@{{ AUTHELIA_PROXY_HOST }}
    identifier: {{ AUTHELIA_PROXY_HOST }}
    subject: "[Authelia] {title}"
    startup_check_address: "{{ AUTHELIA_SMTP_USER }}"
    disable_require_tls: true
    disable_html_emails: false

webauthn:
  disable: false
  display_name: Authelia
  attestation_conveyance_preference: none
  user_verification: preferred
  timeout: 120s

