services:
  ntfy:
    image: binwiederhier/ntfy:{{ NTFY_IMAGE_VERSION }}
    container_name: ntfy
    command:
      - serve
    env_file:
      - ./data/.env
    healthcheck:
      test:
        - CMD-SHELL
        - wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo
          '"healthy"\s*:\s*true' || exit 1
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    volumes:
      - ./data/cache:/var/cache/ntfy:rw
      - ./data/config.yml:/etc/ntfy/server.yml:rw
      - ./data/user.db:/var/lib/ntfy/user.db:rw
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.ntfy.entrypoints=websecure
      - traefik.http.routers.ntfy.rule=Host(`{{ NTFY_PROXY_HOST }}`)
      - traefik.http.routers.ntfy.tls.certResolver=letsencrypt
      - traefik.http.routers.ntfy.middlewares=authelia
      - traefik.http.routers.ntfy.service=ntfy
      - traefik.http.services.ntfy.loadbalancer.server.port=80
    networks:
      - proxy
networks:
  proxy:
    external: true
    name: {{ TRAEFIK_PROXY_NETWORK }}

