---
- name: import pip role
  import_role:
    name: geerlingguy.pip

- name: import docker role
  import_role:
    name: geerlingguy.docker

- name: make sure the required folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ BASE_DIR }}traefik"
    - "{{ BASE_DIR }}traefik/data"

- name: make sure the required files exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: 0600
  loop:
    - "{{ BASE_DIR }}traefik/data/acme.json"

- name: write traefik_yml to host
  ansible.builtin.copy:
    content: |
      IONOS_API_KEY={{ TRAEFIK_IONOS_API_KEY }}
    dest: "{{ BASE_DIR }}/traefik/data/.env"
    owner: root
    group: root
    mode: 0644

- name: copy the dynamic.yml to the host
  ansible.builtin.copy:
    src: files/dynamic.yml
    dest: "{{ BASE_DIR }}traefik/data/dynamic.yml"
    owner: root
    group: root
    mode: 0644

- name: copy the authelia configuration to the host
  template:
    src: configuration.yml
    dest: "{{ BASE_DIR }}traefik/data/configuration.yml"

- name: copy the compose template to the host
  template:
    src: compose.yml
    dest: "{{ BASE_DIR }}traefik/compose.yml"

- name: start stack and wait
  community.docker.docker_compose_v2:
    project_src: "{{ BASE_DIR }}traefik"
    wait: true
