---
- name: make sure the required folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ BASE_DIR }}blog"
    - "{{ BASE_DIR }}blog/data"

- name: copy the compose template to the host
  template:
    src: compose.yml
    dest: "{{ BASE_DIR }}blog/compose.yml"

- name: start stack and wait
  community.docker.docker_compose_v2:
    project_src: "{{ BASE_DIR }}blog"
    wait: true
