---
- name: make sure the required folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ BASE_DIR }}ntfy"
    - "{{ BASE_DIR }}ntfy/data"

- name: touch the user.db file
  ansible.builtin.file:
    path: "{{ BASE_DIR }}ntfy/data/user.db"
    state: touch

- name: write .env to host
  ansible.builtin.copy:
    content: |
      NTFY_ENABLE_LOGIN: true
      NTFY_BEHIND_PROXY: true
      NTFY_BASE_URL: https://{{ NTFY_PROXY_HOST }}
    dest: "{{ BASE_DIR }}/ntfy/data/.env"
    owner: root
    group: root
    mode: 0644

- name: copy the compose template to the host
  template:
    src: compose.yml
    dest: "{{ BASE_DIR }}ntfy/compose.yml"

- name: start stack and wait
  community.docker.docker_compose_v2:
    project_src: "{{ BASE_DIR }}ntfy"
    wait: true
