---
- name: make sure the required folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ BASE_DIR }}ntfy"
    - "{{ BASE_DIR }}ntfy/data"

- name: touch the user.db file
  ansible.builtin.file:
    path: "{{ BASE_DIR }}ntfy/data/user.db"
    state: touch

- name: touch the config.yml file
  ansible.builtin.copy:
    content: |
      auth-file: /var/lib/ntfy/user.db
      auth-default-access: "deny-all"
      behind-proxy: true
      enable-login: false
    dest: "{{ BASE_DIR }}ntfy/data/config.yml"

- name: copy the compose template to the host
  template:
    src: compose.yml
    dest: "{{ BASE_DIR }}ntfy/compose.yml"

- name: start stack and wait
  community.docker.docker_compose_v2:
    project_src: "{{ BASE_DIR }}ntfy"
    wait: true
