all:
  hosts:
    borgardt.me:
      ansible_user: ansible
      ansible_become: true
      ansible_become_method: sudo
      ansible_become_pass: "{{ ansible_become_pass }}"

      borgbackup_version: '0.29.0'
      borgbackup_platform: 'linux64'
      borgbackup_ssh_key_path: '/root/.ssh/id_rsa'
      borg_backups:
        - backup_server: ssh://ansible@localhost
          backup_repository: "~/backups/"
          backup_prefix: '{{ ansible_hostname }}'
          backup_name: '`date +%Y-%m-%d`'
          directories:
            - '/var/lib/docker/volumes/proxymanager_config/'
            - '/var/lib/docker/volumes/proxymanager_letsencrypt/'
          borg_options: '{{ borgbackup_create_default_options }}'