---
- name: make sure the required folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ BASE_DIR }}vaultwarden"
    - "{{ BASE_DIR }}vaultwarden/data"

- name: write .env to host
  ansible.builtin.copy:
    content: |
      PUID=1000
      PGID=1000
      TZ=Europe/Berlin
      ADMIN_TOKEN={{ VAULTWARDEN_ADMIN_TOKEN }}
    dest: "{{ BASE_DIR }}/vaultwarden/data/.env"
    owner: root
    group: root
    mode: 0644

- name: copy the compose template to the host
  template:
    src: compose.yml
    dest: "{{ BASE_DIR }}vaultwarden/compose.yml"

- name: start stack and wait
  community.docker.docker_compose_v2:
    project_src: "{{ BASE_DIR }}vaultwarden"
    wait: true
